apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      containers:
        - name: plex
          image: linuxserver/plex:latest
          ports:
            - containerPort: 32400 # Plex internal web UI
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Etc/UTC"
---
apiVersion: v1
kind: Service
metadata:
  name: plex
spec:
  type: LoadBalancer
  selector:
    app: plex
  ports:
    - name: plex
      port: 5500
      targetPort: 32400
      protocol: TCP
