apiVersion: v1
kind: Secret
metadata:
  name: bigquery-credentials
  namespace: superset
type: Opaque
data:
  service-account-key.json: |
    # Base64 encoded service account JSON key
    # Replace with: cat service-account-key.json | base64 -w 0
    ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAieW91ci1wcm9qZWN0LWlkIiwKICAuLi4KfQ==