apiVersion: apps/v1
kind: Deployment
metadata:
  name: k3s-cd-web
  labels:
    app: k3s-cd-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k3s-cd-web
  template:
    metadata:
      labels:
        app: k3s-cd-web
    spec:
      containers:
        - name: k3s-cd-web
          image: grantc27/grantcampbell-test:96cafb9
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 250m
              memory: 128Mi

---
apiVersion: v1
kind: Service
metadata:
  name: k3s-cd-web-service
spec:
  type: LoadBalancer  # Change to LoadBalancer if needed
  selector:
    app: k3s-cd-web
  ports:
    - port: 8001         # Exposes externally on NodePort/LoadBalancer
      targetPort: 80     # Inside the container
      protocol: TCP