
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k3s-web-app
  labels:
    app: k3s-web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k3s-web-app
  template:
    metadata:
      labels:
        app: k3s-web-app
    spec:
      containers:
        - name: web
          image: grantc27/grantcampbell-test  # Jenkins will update this tag
          ports:
            - containerPort: 800
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: k3s-web-app-service
spec:
  type: LoadBalancer
  selector:
    app: k3s-web-app
  ports:
    - port: 8001
      targetPort: 80
