apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: node-red-pvc # A name for our storage claim
spec:
  accessModes:
    - ReadWriteOnce # This volume can be mounted by a single node
  resources:
    requests:
      storage: 1Gi # Request 1 Gigabyte of storage
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-red
  labels:
    app: node-red
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-red
  template:
    metadata:
      labels:
        app: node-red
    spec:
      containers:
        - name: node-red
          image: nodered/node-red:latest
          ports:
            - containerPort: 1880
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 250m
              memory: 128Mi
          # --- ADD THIS SECTION ---
          # Mount the persistent volume into the container at /data
          volumeMounts:
            - name: node-red-data # This must match the volume name below
              mountPath: /data
      # --- AND ADD THIS SECTION ---
      # Define the volume to be used by the pod
      volumes:
        - name: node-red-data # A name for the volume
          persistentVolumeClaim:
            claimName: node-red-pvc # Use the PVC we created above
---
apiVersion: v1
kind: Service
metadata:
  name: node-red
spec:
  selector:
    app: node-red
  ports:
    - name: mqtt
      protocol: TCP
      port: 1883
      targetPort: 1883
    - name: node-red
      protocol: TCP
      port: 1880
      targetPort: 1880
  type: LoadBalancer
