apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-shell-ttyd
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-shell-ttyd
  template:
    metadata:
      labels:
        app: web-shell-ttyd
    spec:
      hostNetwork: true
      hostPID: true
      containers:
      - name: web-shell
        image: tsl0922/ttyd:latest
        args: ["-p", "7681", "bash"]
        ports:
        - containerPort: 7681
        securityContext:
          privileged: true
          runAsUser: 0
        volumeMounts:
        - name: host-root
          mountPath: /host
        - name: docker-sock
          mountPath: /var/run/docker.sock
      volumes:
      - name: host-root
        hostPath:
          path: /
          type: Directory
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
          type: Socket
---
apiVersion: v1
kind: Service
metadata:
  name: web-shell-ttyd-service
spec:
  selector:
    app: web-shell-ttyd
  ports:
  - port: 7681
    targetPort: 7681
    protocol: TCP
    nodePort: 30083
  type: NodePort