apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-shell-gotty
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-shell-gotty
  template:
    metadata:
      labels:
        app: web-shell-gotty
    spec:
      hostNetwork: true
      hostPID: true
      containers:
      - name: web-shell
        image: sorenisanerd/gotty:latest
        args: ["--port", "8080", "--permit-write", "bash"]
        ports:
        - containerPort: 8080
        securityContext:
          privileged: true
          runAsUser: 0
        volumeMounts:
        - name: host-root
          mountPath: /host
        - name: docker-sock
          mountPath: /var/run/docker.sock
      volumes:
      - name: host-root
        hostPath:
          path: /
          type: Directory
      - name: docker-sock
        hostPath:
          path: /var/run/docker.sock
          type: Socket
---
apiVersion: v1
kind: Service
metadata:
  name: web-shell-gotty-service
spec:
  selector:
    app: web-shell-gotty
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    nodePort: 30083
  type: NodePort